apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-flask
  template:
    metadata:
      labels:
        app: api-flask
    spec:
      containers:
      - name: api-flask
        image: <your-ecr-repo-url>:latest
        ports:
        - containerPort: 5000
